### ISSUE TITLE
bit-granular input

### ISSUE THREAD

**Issue by psvz** [DrSLDR/krock32#1]
Just wanted to make sure I haven't missed it. This package doesn't let one use binary input, such as 0b101010101? Just for entropy encoding: if I had 26 characters to encode 16 bytes (128bits), I would rather prefer to have all 130 bits encoded (26*5 as in base32 definition). That is, if I use 16 bytes as an input I lose 2 bits (130 - 128) with the same coded representation. I would rather give 0b11101.. all 130 bits on the input. It is not possible, or is it?

**Comment by sldr-se** [comment]
I am not _entirely_ sure how to parse your question, but I will try my best to answer.

The library does _not_ allow you to encode an arbitrary number of bits, only an arbitrary number of full bytes. So, yes, encoding 16 bytes (128 bits), would result in 26 encoded characters. That would, in the strictest sense, decode to 130 bits, but the library will encode the surplus two bits as zeros. During decoding, if there are bits at the very end that do not form a whole byte, they are discarded _if and only if_ they are all zeros - if they are not, an exception is raised.

Take a smaller example: encoding a single byte (8 bits). This will also be encoded as 2 characters, representing 10 bits, in the strictest sense.

```python
import krock32
a = b'\xaa'
e = krock32.Encoder()
e.update(a)
s = e.finalize()
print(s)
```

This will print `N8`, where `N` decodes to `10101` (21) and `8` to `01000` (8), where the last two bits of `8` are technically superfluous, and will be ignored. Doing it in reverse:

```python
import krock32
d = krock32.Decoder()
d.update('n8')
a = d.finalize()
print(a)
```

This will print `b'\xaa'`. If we instead change the input to `n9`, which has the bit pattern `10101 01001`, we instead get:

```python
import krock32
d = krock32.Decoder()
d.update('n9')
a = d.finalize()
```

This will raise a `DecoderNonZeroCarryException`, stating that this cannot be decoded into one byte.

**Comment by psvz** [comment]
Hi Jonas @DrSLDR  - and thank you for this comprehensive explainer.
I like this library because it allows to pack the largest amount of entropy into the shortest string that would be user friendly, in a sense that many not technically savvy users would struggle to enter non-alphabetic characters.

What I've done in the end, is actually encoding 17 bytes, and then simply cut 26 characters off the result. Yes, if you attempted to decode it you would get an exception. But my use-case does not require decoding. All I want is 130 bits of entropy.

As you explain, if I encode 16 bytes, I will get 128 bits + 2 bits being always 0. Yet such string is "decodeable" I am missing 2 bits of entropy. So, we could close this issue as I have my solution. On a side note, it might be worthy to extend this library to encode/decode arbitrary number of bits, which is entirely up to you.

**Comment by sldr-se** [comment]
You're welcome. I have a personal preference for base32 due to it being implicitly case insensitive and can eliminate many commonly mis-read characters (`o`,`O`, and `0`, for example). So I agree that it lends itself well to less savvy users.

Regarding extending the library to handle arbitrary amounts of bits, rather than bytes, this won't be done for two reasons:
1. This project is functionally abandoned. It was a fun teaching experience, and while I like the concept, I will be reimplementing it in a compiled language so as to not suffer from Python's relative lack of speed.

2. Doing so would run counter to the Base64/32/16 standard ([RFC 4648](https://www.rfc-editor.org/rfc/rfc4648)) that this work is based on. A fundamental assumption in all those encodings is that the in/outdata will be 8-bit bytes, and breaking that assumption would fundamentally change how the encoding would need to function. Specifically, [section 6](https://www.rfc-editor.org/rfc/rfc4648#section-6) explains how the encoding works _under the assumption that the input is some multiple of 8 bits_. It also explains how "true" Base32 should use padding characters (`=`), but these are excluded in this library (and in [Crockford's alphabet](https://www.crockford.com/base32.html), which it uses) since the correct padding can be derived from the number of characters in the encoded string. This derivation cannot be done for an arbitrary number of bits - how would you, for example, tell the difference between a set of 1, 2, 3, 4, or 5 bits, as they all encode to a single character? I'm not saying it _can't_ be done, but I am saying it no longer falls under the RFC standard, and requires way more thought than I am willing to put into it.

Best of luck with your work - I'll be closing this issue.
